package io.atak.generator;

import com.squareup.javapoet.*;
import io.atak.audit.AtakAuditable;
import io.atak.processor.EntityModel;

import javax.lang.model.element.Modifier;
import java.time.Instant;

/**
 * Generates {@code <Entity>AuditBase} — an abstract JPA-audited base class
 * that the user's entity must extend when {@code @AtakAudit} is present.
 */
public final class AuditGenerator {

    private static final ClassName CREATED_DATE   = ClassName.get("org.springframework.data.annotation", "CreatedDate");
    private static final ClassName LAST_MOD_DATE  = ClassName.get("org.springframework.data.annotation", "LastModifiedDate");
    private static final ClassName CREATED_BY     = ClassName.get("org.springframework.data.annotation", "CreatedBy");
    private static final ClassName LAST_MOD_BY    = ClassName.get("org.springframework.data.annotation", "LastModifiedBy");
    private static final ClassName ENTITY_LISTENERS = ClassName.get("jakarta.persistence", "EntityListeners");
    private static final ClassName AUDITING_ENTITY  = ClassName.get("org.springframework.data.jpa.domain.support", "AuditingEntityListener");
    private static final ClassName COLUMN           = ClassName.get("jakarta.persistence", "Column");
    private static final ClassName MAPPED_SUPERCLASS = ClassName.get("jakarta.persistence", "MappedSuperclass");
    private static final ClassName INSTANT         = ClassName.get(Instant.class);
    private static final ClassName STRING          = ClassName.get(String.class);

    private AuditGenerator() {}

    public static JavaFile generate(EntityModel model) {
        String pkg = model.generatedPackage("audit");

        TypeSpec.Builder cls = TypeSpec.classBuilder(model.auditBaseName())
                .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                .addSuperinterface(ClassName.get(AtakAuditable.class))
                .addAnnotation(MAPPED_SUPERCLASS)
                .addAnnotation(AnnotationSpec.builder(ENTITY_LISTENERS)
                        .addMember("value", "$T.class", AUDITING_ENTITY)
                        .build());

        // createdAt
        cls.addField(FieldSpec.builder(INSTANT, "createdAt", Modifier.PRIVATE)
                .addAnnotation(CREATED_DATE)
                .addAnnotation(AnnotationSpec.builder(COLUMN).addMember("updatable", "false").build())
                .build());

        // updatedAt
        cls.addField(FieldSpec.builder(INSTANT, "updatedAt", Modifier.PRIVATE)
                .addAnnotation(LAST_MOD_DATE)
                .build());

        if (model.auditTrackUser()) {
            // createdBy
            cls.addField(FieldSpec.builder(STRING, "createdBy", Modifier.PRIVATE)
                    .addAnnotation(CREATED_BY)
                    .addAnnotation(AnnotationSpec.builder(COLUMN).addMember("updatable", "false").build())
                    .build());

            // updatedBy
            cls.addField(FieldSpec.builder(STRING, "updatedBy", Modifier.PRIVATE)
                    .addAnnotation(LAST_MOD_BY)
                    .build());
        }

        // implement AtakAuditable
        addGetSet(cls, "createdAt", INSTANT);
        addGetSet(cls, "updatedAt", INSTANT);
        if (model.auditTrackUser()) {
            addGetSet(cls, "createdBy", STRING);
            addGetSet(cls, "updatedBy", STRING);
        } else {
            // no-op implementations when user tracking is disabled
            cls.addMethod(stubGetter("createdBy", STRING));
            cls.addMethod(stubSetter("createdBy", STRING));
            cls.addMethod(stubGetter("updatedBy", STRING));
            cls.addMethod(stubSetter("updatedBy", STRING));
        }

        return JavaFile.builder(pkg, cls.build())
                .addFileComment("Generated by ATAK — your entity must extend this class")
                .build();
    }

    private static void addGetSet(TypeSpec.Builder cls, String name, TypeName type) {
        String cap = DtoGenerator.capitalize(name);
        cls.addMethod(MethodSpec.methodBuilder("get" + cap)
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC).returns(type)
                .addStatement("return this.$L", name).build());
        cls.addMethod(MethodSpec.methodBuilder("set" + cap)
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC).addParameter(type, name)
                .addStatement("this.$L = $L", name, name).build());
    }

    private static MethodSpec stubGetter(String name, TypeName type) {
        return MethodSpec.methodBuilder("get" + DtoGenerator.capitalize(name))
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC).returns(type)
                .addStatement("return null").build();
    }

    private static MethodSpec stubSetter(String name, TypeName type) {
        return MethodSpec.methodBuilder("set" + DtoGenerator.capitalize(name))
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC).addParameter(type, name).build();
    }
}
