package io.atak.generator;

import com.squareup.javapoet.*;
import io.atak.processor.EntityModel;

import javax.lang.model.element.Modifier;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/** Generates {@code <Entity>RequestDto} and {@code <Entity>ResponseDto}. */
public final class DtoGenerator {

    private static final ClassName SCHEMA        = ClassName.get("io.swagger.v3.oas.annotations.media", "Schema");
    private static final ClassName JSON_PROPERTY = ClassName.get("com.fasterxml.jackson.annotation", "JsonProperty");
    private static final ClassName NOT_NULL      = ClassName.get("jakarta.validation.constraints", "NotNull");
    private static final ClassName NOT_BLANK     = ClassName.get("jakarta.validation.constraints", "NotBlank");
    private static final ClassName INSTANT       = ClassName.get(Instant.class);
    private static final ClassName STRING        = ClassName.get(String.class);

    private DtoGenerator() {}

    public static List<JavaFile> generate(EntityModel model) {
        List<JavaFile> files = new ArrayList<>();
        files.add(buildDto(model, true));
        files.add(buildDto(model, false));
        return files;
    }

    private static JavaFile buildDto(EntityModel model, boolean isRequest) {
        String dtoName = isRequest ? model.requestDtoName() : model.responseDtoName();
        String pkg     = model.generatedPackage("dto");

        TypeSpec.Builder cls = TypeSpec.classBuilder(dtoName)
                .addModifiers(Modifier.PUBLIC);

        if (model.openApi()) {
            cls.addAnnotation(AnnotationSpec.builder(SCHEMA)
                    .addMember("description", "$S",
                            model.simpleName() + (isRequest ? " request" : " response") + " payload")
                    .build());
        }

        for (EntityModel.FieldModel f : model.fields()) {
            if (isRequest  && !f.inRequest())  continue;
            if (!isRequest && !f.inResponse()) continue;

            addField(cls, model, f.name(), f.typeName(), f.description(), f.example(),
                     f.required(), f.jsonName(), isRequest);
        }

        // V3 — audit fields appended to ResponseDto only
        if (!isRequest && model.hasAudit()) {
            addAuditFields(cls, model);
        }

        addGettersSetters(cls, model, isRequest);

        return JavaFile.builder(pkg, cls.build())
                .addFileComment("Generated by ATAK — do not edit manually")
                .build();
    }

    private static void addField(TypeSpec.Builder cls, EntityModel model,
                                 String name, String typeName,
                                 String description, String example,
                                 boolean required, String jsonName,
                                 boolean isRequest) {
        TypeName fieldType = resolveType(typeName);
        FieldSpec.Builder fb = FieldSpec.builder(fieldType, name, Modifier.PRIVATE);

        if (!jsonName.equals(name)) {
            fb.addAnnotation(AnnotationSpec.builder(JSON_PROPERTY)
                    .addMember("value", "$S", jsonName).build());
        }

        if (model.openApi()) {
            AnnotationSpec.Builder schemaAnn = AnnotationSpec.builder(SCHEMA);
            if (!description.isBlank()) schemaAnn.addMember("description", "$S", description);
            if (!example.isBlank())     schemaAnn.addMember("example", "$S", example);
            if (required)               schemaAnn.addMember("required", "$L", true);
            fb.addAnnotation(schemaAnn.build());
        }

        if (isRequest && required) {
            fb.addAnnotation(fieldType.equals(ClassName.get(String.class)) ? NOT_BLANK : NOT_NULL);
        }

        cls.addField(fb.build());
    }

    private static void addAuditFields(TypeSpec.Builder cls, EntityModel model) {
        String[] names = model.auditTrackUser()
                ? new String[]{"createdAt", "updatedAt", "createdBy", "updatedBy"}
                : new String[]{"createdAt", "updatedAt"};

        for (String name : names) {
            boolean isInstant = name.endsWith("At");
            TypeName t = isInstant ? INSTANT : STRING;
            FieldSpec.Builder fb = FieldSpec.builder(t, name, Modifier.PRIVATE);
            if (model.openApi()) {
                fb.addAnnotation(AnnotationSpec.builder(SCHEMA)
                        .addMember("description", "$S", auditDesc(name)).build());
            }
            cls.addField(fb.build());
        }
    }

    private static String auditDesc(String field) {
        return switch (field) {
            case "createdAt"  -> "Timestamp when this record was created";
            case "updatedAt"  -> "Timestamp of the last update";
            case "createdBy"  -> "User who created this record";
            case "updatedBy"  -> "User who last updated this record";
            default           -> field;
        };
    }

    private static void addGettersSetters(TypeSpec.Builder cls, EntityModel model, boolean isRequest) {
        for (EntityModel.FieldModel f : model.fields()) {
            if (isRequest  && !f.inRequest())  continue;
            if (!isRequest && !f.inResponse()) continue;
            TypeName t = resolveType(f.typeName());
            String   cap = capitalize(f.name());
            cls.addMethod(getter(cap, t, f.name()));
            cls.addMethod(setter(cap, t, f.name()));
        }

        if (!isRequest && model.hasAudit()) {
            String[] names = model.auditTrackUser()
                    ? new String[]{"createdAt", "updatedAt", "createdBy", "updatedBy"}
                    : new String[]{"createdAt", "updatedAt"};
            for (String name : names) {
                TypeName t = name.endsWith("At") ? INSTANT : STRING;
                cls.addMethod(getter(capitalize(name), t, name));
                cls.addMethod(setter(capitalize(name), t, name));
            }
        }
    }

    private static MethodSpec getter(String cap, TypeName t, String field) {
        return MethodSpec.methodBuilder("get" + cap)
                .addModifiers(Modifier.PUBLIC).returns(t)
                .addStatement("return this.$L", field).build();
    }

    private static MethodSpec setter(String cap, TypeName t, String field) {
        return MethodSpec.methodBuilder("set" + cap)
                .addModifiers(Modifier.PUBLIC).addParameter(t, field)
                .addStatement("this.$L = $L", field, field).build();
    }

    static TypeName resolveType(String typeName) {
        try { return ClassName.bestGuess(typeName); }
        catch (IllegalArgumentException e) { return primitiveToBoxed(typeName); }
    }

    private static TypeName primitiveToBoxed(String typeName) {
        return switch (typeName) {
            case "int"     -> ClassName.get(Integer.class);
            case "long"    -> ClassName.get(Long.class);
            case "double"  -> ClassName.get(Double.class);
            case "float"   -> ClassName.get(Float.class);
            case "boolean" -> ClassName.get(Boolean.class);
            case "char"    -> ClassName.get(Character.class);
            case "byte"    -> ClassName.get(Byte.class);
            case "short"   -> ClassName.get(Short.class);
            default        -> ClassName.get(Object.class);
        };
    }

    static String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }
}
