package io.atak.generator;

import com.squareup.javapoet.*;
import io.atak.processor.EntityModel;

import javax.lang.model.element.Modifier;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates {@code <Entity>Filter} (query DTO) and {@code <Entity>Specification}
 * (JPA {@code Specification} implementation) when any field carries {@code @AtakFilter}.
 */
public final class FilterGenerator {

    private static final ClassName SPECIFICATION    = ClassName.get("org.springframework.data.jpa.domain", "Specification");
    private static final ClassName CRITERIA_BUILDER = ClassName.get("jakarta.persistence.criteria", "CriteriaBuilder");
    private static final ClassName CRITERIA_QUERY   = ClassName.get("jakarta.persistence.criteria", "CriteriaQuery");
    private static final ClassName ROOT             = ClassName.get("jakarta.persistence.criteria", "Root");
    private static final ClassName PREDICATE        = ClassName.get("jakarta.persistence.criteria", "Predicate");
    private static final ClassName ARRAY_LIST       = ClassName.get("java.util", "ArrayList");
    private static final ClassName LIST_TYPE        = ClassName.get("java.util", "List");
    private static final ClassName SCHEMA           = ClassName.get("io.swagger.v3.oas.annotations.media", "Schema");

    private FilterGenerator() {}

    public static List<JavaFile> generate(EntityModel model) {
        List<JavaFile> files = new ArrayList<>();
        files.add(buildFilterDto(model));
        files.add(buildSpecification(model));
        return files;
    }

    // ---- <Entity>Filter -------------------------------------------------

    private static JavaFile buildFilterDto(EntityModel model) {
        String pkg = model.generatedPackage("filter");
        TypeSpec.Builder cls = TypeSpec.classBuilder(model.filterDtoName())
                .addModifiers(Modifier.PUBLIC);

        if (model.openApi()) {
            cls.addAnnotation(AnnotationSpec.builder(SCHEMA)
                    .addMember("description", "$S", "Filter parameters for " + model.simpleName() + " queries")
                    .build());
        }

        for (EntityModel.FieldModel f : model.filterableFields()) {
            switch (f.filterType()) {
                case LIKE, EQUALS -> addFilterField(cls, model, f.name(), f.typeName(), f.description());
                case RANGE -> {
                    addFilterField(cls, model, "min" + DtoGenerator.capitalize(f.name()), f.typeName(),
                            "Minimum " + f.name());
                    addFilterField(cls, model, "max" + DtoGenerator.capitalize(f.name()), f.typeName(),
                            "Maximum " + f.name());
                }
                case IN -> {
                    TypeName listType = ParameterizedTypeName.get(LIST_TYPE, resolveType(f.typeName()));
                    addFilterFieldTyped(cls, model, f.name() + "In", listType,
                            "Filter by list of " + f.name() + " values");
                }
            }
        }

        // getters + setters
        for (EntityModel.FieldModel f : model.filterableFields()) {
            switch (f.filterType()) {
                case LIKE, EQUALS -> addGetterSetter(cls, f.name(), resolveType(f.typeName()));
                case RANGE -> {
                    String cap = DtoGenerator.capitalize(f.name());
                    TypeName t = resolveType(f.typeName());
                    addGetterSetter(cls, "min" + cap, t);
                    addGetterSetter(cls, "max" + cap, t);
                }
                case IN -> {
                    TypeName listType = ParameterizedTypeName.get(LIST_TYPE, resolveType(f.typeName()));
                    addGetterSetter(cls, f.name() + "In", listType);
                }
            }
        }

        return JavaFile.builder(pkg, cls.build())
                .addFileComment("Generated by ATAK — do not edit manually")
                .build();
    }

    private static void addFilterField(TypeSpec.Builder cls, EntityModel model,
                                       String name, String typeName, String desc) {
        FieldSpec.Builder fb = FieldSpec.builder(resolveType(typeName), name, Modifier.PRIVATE);
        if (model.openApi() && !desc.isBlank()) {
            fb.addAnnotation(AnnotationSpec.builder(SCHEMA)
                    .addMember("description", "$S", desc).build());
        }
        cls.addField(fb.build());
    }

    private static void addFilterFieldTyped(TypeSpec.Builder cls, EntityModel model,
                                            String name, TypeName typeName, String desc) {
        FieldSpec.Builder fb = FieldSpec.builder(typeName, name, Modifier.PRIVATE);
        if (model.openApi() && !desc.isBlank()) {
            fb.addAnnotation(AnnotationSpec.builder(SCHEMA)
                    .addMember("description", "$S", desc).build());
        }
        cls.addField(fb.build());
    }

    private static void addGetterSetter(TypeSpec.Builder cls, String name, TypeName type) {
        String cap = DtoGenerator.capitalize(name);
        cls.addMethod(MethodSpec.methodBuilder("get" + cap)
                .addModifiers(Modifier.PUBLIC).returns(type)
                .addStatement("return this.$L", name).build());
        cls.addMethod(MethodSpec.methodBuilder("set" + cap)
                .addModifiers(Modifier.PUBLIC).addParameter(type, name)
                .addStatement("this.$L = $L", name, name).build());
    }

    // ---- <Entity>Specification ------------------------------------------

    private static JavaFile buildSpecification(EntityModel model) {
        String pkg       = model.generatedPackage("filter");
        ClassName entity = ClassName.get(model.packageName(), model.simpleName());
        ClassName filter = ClassName.get(pkg, model.filterDtoName());
        TypeName  spec   = ParameterizedTypeName.get(SPECIFICATION, entity);

        TypeSpec.Builder cls = TypeSpec.classBuilder(model.specificationName())
                .addModifiers(Modifier.PUBLIC)
                .addSuperinterface(spec);

        // constructor
        cls.addField(FieldSpec.builder(filter, "filter", Modifier.PRIVATE, Modifier.FINAL).build());
        cls.addMethod(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addParameter(filter, "filter")
                .addStatement("this.filter = filter")
                .build());

        // toPredicate
        ParameterizedTypeName rootType  = ParameterizedTypeName.get(ROOT, entity);
        ParameterizedTypeName queryType = ParameterizedTypeName.get(CRITERIA_QUERY, WildcardTypeName.subtypeOf(Object.class));

        MethodSpec.Builder toPredicate = MethodSpec.methodBuilder("toPredicate")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(PREDICATE)
                .addParameter(rootType, "root")
                .addParameter(queryType, "query")
                .addParameter(CRITERIA_BUILDER, "cb")
                .addStatement("$T<$T> predicates = new $T<>()", LIST_TYPE, PREDICATE, ARRAY_LIST);

        for (EntityModel.FieldModel f : model.filterableFields()) {
            String cap = DtoGenerator.capitalize(f.name());
            switch (f.filterType()) {
                case LIKE -> toPredicate.addCode(
                        "if (filter.get$L() != null) {\n" +
                        "    predicates.add(cb.like(cb.lower(root.get($S)), \"%\" + filter.get$L().toLowerCase() + \"%\"));\n" +
                        "}\n", cap, f.name(), cap);
                case EQUALS -> toPredicate.addCode(
                        "if (filter.get$L() != null) {\n" +
                        "    predicates.add(cb.equal(root.get($S), filter.get$L()));\n" +
                        "}\n", cap, f.name(), cap);
                case RANGE -> {
                    String minCap = "Min" + cap;
                    String maxCap = "Max" + cap;
                    toPredicate.addCode(
                            "if (filter.get$L() != null) {\n" +
                            "    predicates.add(cb.greaterThanOrEqualTo(root.get($S), filter.get$L()));\n" +
                            "}\n", minCap, f.name(), minCap);
                    toPredicate.addCode(
                            "if (filter.get$L() != null) {\n" +
                            "    predicates.add(cb.lessThanOrEqualTo(root.get($S), filter.get$L()));\n" +
                            "}\n", maxCap, f.name(), maxCap);
                }
                case IN -> {
                    String inCap = cap + "In";
                    toPredicate.addCode(
                            "if (filter.get$L() != null && !filter.get$L().isEmpty()) {\n" +
                            "    predicates.add(root.get($S).in(filter.get$L()));\n" +
                            "}\n", inCap, inCap, f.name(), inCap);
                }
            }
        }

        toPredicate.addStatement("return cb.and(predicates.toArray(new $T[0]))", PREDICATE);
        cls.addMethod(toPredicate.build());

        return JavaFile.builder(pkg, cls.build())
                .addFileComment("Generated by ATAK — do not edit manually")
                .build();
    }

    static TypeName resolveType(String typeName) {
        try { return ClassName.bestGuess(typeName); }
        catch (IllegalArgumentException e) {
            return switch (typeName) {
                case "int"     -> ClassName.get(Integer.class);
                case "long"    -> ClassName.get(Long.class);
                case "double"  -> ClassName.get(Double.class);
                case "float"   -> ClassName.get(Float.class);
                case "boolean" -> ClassName.get(Boolean.class);
                default        -> ClassName.get(Object.class);
            };
        }
    }
}
