package io.atak.generator;

import com.squareup.javapoet.*;
import io.atak.processor.EntityModel;

import javax.lang.model.element.Modifier;
import java.time.Instant;

/** Generates a hand-rolled mapper between entity and DTOs (no MapStruct dependency). */
public final class MapperGenerator {

    private static final ClassName COMPONENT = ClassName.get("org.springframework.stereotype", "Component");
    private static final ClassName INSTANT   = ClassName.get(Instant.class);
    private static final ClassName STRING    = ClassName.get(String.class);

    private MapperGenerator() {}

    public static JavaFile generate(EntityModel model) {
        String pkg         = model.generatedPackage("mapper");
        String dtoReqPkg   = model.generatedPackage("dto");
        String dtoRespPkg  = model.generatedPackage("dto");

        ClassName entityCls   = ClassName.get(model.packageName(), model.simpleName());
        ClassName requestCls  = ClassName.get(dtoReqPkg, model.requestDtoName());
        ClassName responseCls = ClassName.get(dtoRespPkg, model.responseDtoName());
        ClassName auditable   = ClassName.get("io.atak.audit", "AtakAuditable");

        TypeSpec.Builder cls = TypeSpec.classBuilder(model.mapperName())
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(COMPONENT);

        // toEntity(RequestDto) → Entity
        MethodSpec.Builder toEntity = MethodSpec.methodBuilder("toEntity")
                .addModifiers(Modifier.PUBLIC)
                .returns(entityCls)
                .addParameter(requestCls, "dto")
                .addStatement("$T entity = new $T()", entityCls, entityCls);

        for (EntityModel.FieldModel f : model.fields()) {
            if (!f.inRequest()) continue;
            toEntity.addStatement("entity.set$L(dto.get$L())",
                    DtoGenerator.capitalize(f.name()), DtoGenerator.capitalize(f.name()));
        }

        if (model.hasTenant()) {
            ClassName tenantCtx = ClassName.get("io.atak.tenant", "TenantContext");
            toEntity.addStatement("entity.set$L($T.current())",
                    DtoGenerator.capitalize(model.tenantFieldName()), tenantCtx);
        }

        toEntity.addStatement("return entity");
        cls.addMethod(toEntity.build());

        // toResponse(Entity) → ResponseDto
        MethodSpec.Builder toResponse = MethodSpec.methodBuilder("toResponse")
                .addModifiers(Modifier.PUBLIC)
                .returns(responseCls)
                .addParameter(entityCls, "entity")
                .addStatement("$T dto = new $T()", responseCls, responseCls);

        for (EntityModel.FieldModel f : model.fields()) {
            if (!f.inResponse()) continue;
            toResponse.addStatement("dto.set$L(entity.get$L())",
                    DtoGenerator.capitalize(f.name()), DtoGenerator.capitalize(f.name()));
        }

        if (model.hasAudit()) {
            toResponse.beginControlFlow("if (entity instanceof $T auditable)", auditable);
            toResponse.addStatement("dto.setCreatedAt(auditable.getCreatedAt())");
            toResponse.addStatement("dto.setUpdatedAt(auditable.getUpdatedAt())");
            if (model.auditTrackUser()) {
                toResponse.addStatement("dto.setCreatedBy(auditable.getCreatedBy())");
                toResponse.addStatement("dto.setUpdatedBy(auditable.getUpdatedBy())");
            }
            toResponse.endControlFlow();
        }

        toResponse.addStatement("return dto");
        cls.addMethod(toResponse.build());

        // updateEntity(Entity, RequestDto)
        MethodSpec.Builder update = MethodSpec.methodBuilder("updateEntity")
                .addModifiers(Modifier.PUBLIC)
                .addParameter(entityCls, "entity")
                .addParameter(requestCls, "dto");

        for (EntityModel.FieldModel f : model.fields()) {
            if (!f.inRequest()) continue;
            update.addStatement("entity.set$L(dto.get$L())",
                    DtoGenerator.capitalize(f.name()), DtoGenerator.capitalize(f.name()));
        }
        cls.addMethod(update.build());

        return JavaFile.builder(pkg, cls.build())
                .addFileComment("Generated by ATAK — do not edit manually")
                .build();
    }
}
