package io.atak.generator;

import com.squareup.javapoet.*;
import io.atak.processor.EntityModel;

import javax.lang.model.element.Modifier;

/** Generates a Spring Data JPA repository interface. */
public final class RepositoryGenerator {

    private static final ClassName JPA_REPOSITORY  =
            ClassName.get("org.springframework.data.jpa.repository", "JpaRepository");
    private static final ClassName JPA_SPEC_EXEC   =
            ClassName.get("org.springframework.data.jpa.repository", "JpaSpecificationExecutor");
    private static final ClassName REPOSITORY      =
            ClassName.get("org.springframework.stereotype", "Repository");

    private RepositoryGenerator() {}

    public static JavaFile generate(EntityModel model) {
        String pkg      = model.generatedPackage("repository");
        ClassName entity = ClassName.get(model.packageName(), model.simpleName());
        TypeName  idType;
        try { idType = ClassName.bestGuess(model.idType()); }
        catch (IllegalArgumentException e) { idType = ClassName.get(Long.class); }

        TypeSpec.Builder repo = TypeSpec.interfaceBuilder(model.repositoryName())
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(REPOSITORY)
                .addSuperinterface(ParameterizedTypeName.get(JPA_REPOSITORY, entity, idType));

        // V2/V4 — add JpaSpecificationExecutor when filters or multi-tenant are enabled
        if (model.needsSpecificationExecutor()) {
            repo.addSuperinterface(ParameterizedTypeName.get(JPA_SPEC_EXEC, entity));
        }

        return JavaFile.builder(pkg, repo.build())
                .addFileComment("Generated by ATAK — do not edit manually")
                .build();
    }
}
